=== phughk/laerning-tool/laerning-module.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="learning-module">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="metadata"/>
                <xs:element ref="entries"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="metadata">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="author" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="updated" type="xs:string" />
                <xs:element name="file-version" type="xs:string" />
                <xs:element name="format-version" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="entries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="entry" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="entry">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="question" type="xs:string" />
                <xs:element name="category-declaration" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="id" type="xs:string" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="answer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="correct" type="xs:boolean" />
                                <xs:attribute name="id" type="xs:string" />
                                <xs:attribute name="category" type="xs:string" use="optional"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" />
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="sampleable" type="xs:boolean" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== phughk/laerning-tool/engine/data/sample-1.0.0.xml
<?xml version="1.0" encoding="utf-8" ?>
<learning-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../laerning-module.xsd">
    <metadata>
        <name>Sample Dataset</name>
        <author>Hugh Kaznowski</author>
        <description>Demo of capability</description>
        <updated>2022.12.02 22:07</updated>
        <file-version>1.0.0</file-version>
        <format-version>1.0.0</format-version>
    </metadata>
    <entries>
        <entry type="single-choice" id="five_larger_than_three">
            <question>Is 5 larger than 3?</question>
            <answer correct="true" id="yes">Yes</answer>
            <answer correct="false" id="no">No</answer>
        </entry>
        <entry type="multiple-choice" id="primary_colours" sampleable="true">
            <question>Which of the following are primary colours</question>
            <answer correct="true" id="red">Red</answer>
            <answer correct="true" id="yellow">Yellow</answer>
            <answer correct="true" id="blue">Blue</answer>
            <answer correct="false" id="green">Green</answer>
            <answer correct="false" id="m">Magenta</answer>
        </entry>
        <entry type="category" id="verb_noun_adjective" sampleable="true">
            <question>Match the words to the parts of a sentence</question>
            <category-declaration id="verb">Verb</category-declaration>
            <category-declaration id="noun">Noun</category-declaration>
            <category-declaration id="adjective">Adjective</category-declaration>
            <answer category="verb" id="v_laugh">Laughing</answer> <!-- This could hypothetically be (to) "Happy", conflicting with adjective. Then both categories are valid-->
            <answer category="noun" id="n_happ">Happiness</answer>
            <answer category="adjective" id="a_happ">Happy</answer>
        </entry>
    </entries>
</learning-module>

=== phughk/laerning-tool/engine/data/millionaire-1.0.0.xml
<?xml version="1.0" encoding="utf-8" ?>
<learning-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../laerning-module.xsd">
    <metadata>
        <name>Millionaire</name>
        <author>Hugh Kaznowski</author>
        <description>Demonstrate a simple quiz. It is deliberately small, because I needed a different dataset to the sample.</description>
        <updated>2022.12.05 22:07</updated>
        <file-version>1.0.0</file-version>
        <format-version>1.0.0</format-version>
    </metadata>
    <entries>
        <entry type="single-choice" id="six_pack">
            <question>A person with well-developed abdominal muscles is said to have a what?</question>
            <answer correct="false" id="one">One-pack</answer>
            <answer correct="false" id="twelve">Twelve-pack</answer>
            <answer correct="true" id="six">Six-pack</answer>
            <answer correct="false" id="family">Family-pack</answer>
        </entry>
        <entry type="single-choice" id="film_end">
            <question>Which two words traditionally appear onscreen at the termination of a feature film?</question>
            <answer correct="true" id="end">The End</answer>
            <answer correct="false" id="finish">The Finish</answer>
            <answer correct="false" id="conclusion">The Conclusion</answer>
            <answer correct="false" id="pizza">The Pizza Rolls Are Done</answer>
        </entry>
    </entries>
</learning-module>
